### PR TITLE
Improve ContactList layout and improve subtitle line breaking

### PR DESCRIPTION
**Pull request by Supereg**
# Improve ContactList layout and improve subtitle line breaking

## :recycle: Current situation & Problem
Currently, the `ContactsList` view is built using a custom ScrollView implementation and drawing custom backgrounds with shades around the `ContactView`s. This doesn't really feel native on iOS. Instead, this PR rethinks the implementation by rebuilding the `ContactsList` view using SwiftUI standard components like `List`. This makes the `ContactsList` now feel right at home.
Further, previously the subtitle, consisting of the Person's title and organization, was built using multiple distinct `Text` instances. This caused problems when the text was longer than the view was capable of displaying. This PR ensures that a persons title and organization are combined into a single `Text` view and allows to to wrap into a second line.
Lastly, this PR migrates the PR to use String catalogs, optimizes key naming and bumps the target to iOS 17.

Below are two screenshots comparing the previous implementation to the updated one.

Bildschirmfoto 2023-11-01 um 22 13 11
Bildschirmfoto 2023-11-01 um 22 12 14

## :gear: Release Notes 
* New updated visuals for the `ContactsView` that feel way more native to iOS
* Updated line breaking behavior for too long contact subtitles (title and organization)
* Migrated to use String Catalogs for localization

## :books: Documentation
--

## :white_check_mark: Testing
Tests were slightly adjusted, due to issues with line breaks in the labels.

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — APPROVED** [review]
Thank you for the great improvements; this looks great @Supereg! 🚀

**Comment by Supereg** [comment]
Will tag the new SpeziViews later on and still include it in this PR.

**Comment by vishnuravi** [comment]
This looks much better! Thank you @Supereg!

**Review by PSchmiedmayer — APPROVED** [review]
👍🚀

**Pull request merged**
